### ISSUE TITLE
Long edges in random delaunay graphs

### ISSUE THREAD

**Issue by tzovas** [sebalamm/KaGen#5]
Hello,

I create some function to also store the coordinates of geometric graphs
and use them to visualize them. In the delaunay generator, it looks like 
vertices on the one side of space are connected with vertices one the
opposite side; like creating a torus. This does not seem to happen in
the random geometric graphs.

Not sure if this is a bug. This could easily be a mistake on the way I print 
the coordinates.

Can you verify/dismiss this behaviour?

Best,
Harry

**Comment by tzovas** [comment]
Hi Sebastian,

I am not sure I get it. The purpose of the periodic boundary condition is to get rid of the long edges?
(with "long edges" I mean edges of length almost 1 in the unit square; these are between non-neighbouring vertices, e.g, one vertex is at (0.0, 0.5) and the other at (1.0, 0.5). )
But these edges do exist...
Maybe I am using it the wrong way?

**Comment by tzovas** [comment]
If there is any follow up info on this, it would be helpful.

**Comment by schulzchristian** [comment]
Hi Harry,

I shortly spoke to Sebastian, we are unsure if we understand your problem. Could you please clarify it more?
Are you suggesting that the code does not run correctly? As Sebastian said, the long edges result probably from the periodic boundary condition.

Best
Christian

**Comment by tzovas** [comment]
Hi,
I think so, that there are edges that should not be there.
For example, there could be an edge from a point with x coord near 0, to a point in the "other side", with x coord near 1.
Actually, I do not know if this kind of edges should exist or not. They do not belong in the 2d delaunay triangulation.

As I said, I created some functions to store the coordinates so this might be an error on my side.

Best,
Harry

**Comment by schulzchristian** [comment]
But we do have periodic boundary conditions, so the edges should be there because the points are close, aren't they?

**Comment by schulzchristian** [comment]
@sebalamm is there a way to disable periodic boundary conditions?

**Comment by sebalamm** [comment]
Currently, there is no option to disable the boundary condition.
Since Daniel implemented the generator, I would have to ask him if this can be done easily.
I suppose it is, since the actual triangulation is competed using CGAL.
However, the scalability will definitely take a hit, as the halo of a cell on the border can be significantly larger than it is right now.
@tzovas Can you send me the parameters you're using, so I can double check the edges?

**Comment by dfunke** [comment]
Disabling the periodic boundary condition is certainly possible, but would require quite some testing and cause asymmetry between the PEs at the boundary and the ones in the interior.

**Comment by tzovas** [comment]
Sorry for the late answer, I had to dig up some info.

An output from a call is seen below. I used the 2d rdg generator called with 16 MPI processes/cores.

> generate graph (n=1073741824, k=16, s=1, P=16)
%%Calling command: kagen -output_dir ./distr -n 30 -gen rdg_2d 
%%Called with 16 MPI processes
%%running in bcn1320
\### before calling generator
\### generator finished
done generating graph, time: 72.5032, total number of edges: 3221836347, write output...

I believe that this does not happen with the rgg generator, which I guess does not use the periodic boundary condition.
But i am not 100% sure of that.

**Comment by schulzchristian** [comment]
Hi Harry, I don't understand where the problem is tbh, 
is the problem that the Delaunay generator uses the periodic boundary condition and the rgg does not? Do you need other versions of the algorithms?

Best
Christian

**Comment by tzovas** [comment]
The rdg_2d creates points in the unit square, right?
I would expect that the distance between two connected points is "low".
By low, i mean less than 1 at least.
But I find pair of vertices that have even distance more than 1 and generally
points that are not connected to their "near neighbours".

Is this normal/expected behaviour?
Does this graph correspond to a delaunay triangulation?

**Comment by schulzchristian** [comment]
Hi Harry,

Could it be that you are not correctly measuring distance? If you have periodic boundary conditions, there you should use the ``smallest'' distance. If you feel that something is not working correctly, could you provide us with small examples and outputs of our program so that we can have a look at it?
 
Note that the delaunay triangulation looks different when using periodic boundary conditions.

Best
Christian

**Comment by tzovas** [comment]
Just to be clear: I wrote the code to store the coordinates and it is very likely that
the error is there. In the process of doing so, I might have also changed (willingly
or not) other parts of the code,

I attach an rdg with 2^5 nodes created with 
`mpirun -n 4 ./installation/bin/kagen -gen rdg_2d -n 5 -output_dir tmp`

Also a notebook (and the same in python) that reads the graph using NetworKit
and measures the distance between connected vertices. The last part also exports
the graph to [gephi](https://gephi.org/) (you will need the Graph Streaming and GeoLayout
plugins in Gephi to make that work -- in the streaming window, right click to start the
Master serve before exporting).

I also attach an image of the whole graph and one that a specific vertex with an "long" edge 
is highlighted

![rdg_2d_5](https://user-images.githubusercontent.com/16034714/87693450-4a5ac400-c78d-11ea-9409-33426d1688b2.png)
![rdg_2d_5_v](https://user-images.githubusercontent.com/16034714/87693454-4af35a80-c78d-11ea-9aae-61559376e5c1.png)

[check_rdg_2d.tar.gz](https://github.com/sebalamm/KaGen/files/4932552/check_rdg_2d.tar.gz)

**Comment by schulzchristian** [comment]
yes, but it is a long edge since you draw it long, isnt it? Technically, you should put that thing on a sphere and draw that edge the other way around... this is what the periodic boundary condition means. Apart from that, I am not sure how we can help

**Comment by dfunke** [comment]
Hi Harry,

thank you for your example. I put together a quick patch that prevents the periodic edges from being output. Notice that internally the triangulation still uses the periodic boundary condition, but maybe this suffices already for you needs.

Give it a try and let me know whether this enough for you or whether you need a true non-periodic DT.

[only_contained_edges.patch.txt](https://github.com/sebalamm/KaGen/files/4932688/only_contained_edges.patch.txt)
