### ISSUE TITLE
Seed Ignored

### ISSUE THREAD

**Issue by schulzchristian** [sebalamm/KaGen#7]
Hi Sebastian,
 
for some graph classes the seed seems to be ignored (i.e. rhg). I use different seeds but get the same result as a graph.

Best
Christian

**Comment by sebalamm** [comment]
Can't reproduce it. Can you give me an example?

**Comment by schulzchristian** [comment]
Sorry, my mistake, I used -seed=$seed in my scripts. It does not complain and uses seed 1 in this case. -seed $seed as argument works perfectly fine.
